### ISSUE TITLE
contradiction in "Rights to your contributions"

### ISSUE THREAD

**Issue by nikitakoselev** [Green-Software-Foundation/Carbon_CI_Pipeline_Tooling#31]
These 2 points contradict each other.
1st states that you must have authored 100% and 2nd explain that it's not necessary to author 100%.
I suggest this case is raised as a good first-time issue for some friendly technical writer to fix.

Agree that you have authored 100% of the content
...
Agree that, if you did not author 100% of the content, the appropriate licenses and copyrights have been added along with any other necessary attribution.

File: https://github.com/Green-Software-Foundation/Carbon_CI_Pipeline_Tooling/blob/Dev/CONTRIBUTING.md

Screenshot: ![image](https://user-images.githubusercontent.com/6383738/200781029-ed768aea-616c-4a1a-a365-8b0697cc61b9.png)

**Comment by Sealjay** [comment]
Ah, true. Looks like the original contributing file hasn't been changed since @Avanade first donated the code.

I've updated it in Avanade's contributing file, but good flag for this project.

**Comment by FergusKidd** [comment]
Thank you @nikitakoselev - have updated this in the dev branch to remove the contradiction.
